name: deepforest-modal-app
channels:
  - conda-forge
dependencies:
  - ipython=9.3.0
  - gdal=3.11.0
  - myst-parser=4.0.1
  - nbsphinx=0.9.7
  - openpyxl=3.1.5
  - pip=25.1.1
  - pooch=1.8.2
  - pydata-sphinx-theme=0.16.1
  - python=3.13
  - setuptools=80.9.0
  - sphinx=8.2.3
  - tqdm=4.67.1
